#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
M3D-RefSeg (npy-prepared) Exploratory Data Analysis (EDA)

Input:
- CSV: columns [Image, Mask, Mask_ID, Question_Type, Question, Answer]
- npy_root/: case folders sXXXX/ containing ct.npy, mask.npy, text.json
  (generated by the official prepare script)

Outputs (out_dir/):
- tables/*.csv, *.json
- figs/*.png (histograms, bar charts, t-SNE)
- overlays/*.png (optional qualitative QC)

Run:
  python eda_m3d_refseg_npy.py --csv ... --npy_root ... --out_dir ... --text_eda ...
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
from tqdm import tqdm


# ---------------------------
# Heuristics for text EDA
# ---------------------------

UNCERTAINTY_TERMS = [
    "possible", "possibly", "probable", "probably", "likely", "unlikely",
    "may", "might", "could", "consider", "considering", "suggest", "suggests",
    "suspicious", "suspected", "cannot exclude", "can't exclude", "rule out",
    "appears", "appearance of", "compatible with", "consistent with"
]
NEGATION_TERMS = [
    "no ", "not ", "without", "absence of", "negative for", "free of", "denies"
]
LATERALITY_TERMS = {
    "left": [" left ", "left-sided", "left side", " left.", "left "],
    "right": [" right ", "right-sided", "right side", " right.", "right "],
    "bilateral": ["bilateral", "both sides", "both lungs", "both kidneys"],
}
ANATOMY_GROUPS = {
    "cardio_vascular": ["heart", "cardiac", "coronary", "aorta", "artery", "vein"],
    "pulmonary": ["lung", "pulmonary", "pleura", "bronch", "airway"],
    "hepato_biliary": ["liver", "hepatic", "gallbladder", "biliary"],
    "renal_urinary": ["kidney", "renal", "ureter", "bladder", "pelvis"],
    "gastro_intestinal": ["stomach", "bowel", "colon", "rectum", "pancreas", "spleen"],
    "neuro_headneck": ["brain", "cerebral", "intracranial", "skull", "sinus"],
    "musculoskeletal": ["bone", "vertebra", "spine", "femur", "rib", "fracture"],
    "reproductive": ["prostate", "uterus", "ovary", "testis"],
}


# ---------------------------
# Utilities
# ---------------------------

def ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)

def parse_case_id(path_str: str) -> str:
    """Extract 'sXXXX' from a path like 's0736/ct.nii.gz' or 's0736\\ct.npy'."""
    parts = re.split(r"[\\/]+", str(path_str).strip())
    return parts[0] if parts else str(path_str)

def safe_read_json(path: Path) -> Optional[dict]:
    try:
        with path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None

def load_npy_3d(path: Path) -> np.ndarray:
    """Load npy and return a 3D array (D,H,W). Accepts [1,D,H,W] or [D,H,W]."""
    arr = np.load(str(path), mmap_mode="r")
    arr = np.asarray(arr)
    if arr.ndim == 4 and arr.shape[0] == 1:
        arr = arr[0]
    if arr.ndim != 3:
        raise ValueError(f"Expected 3D array after squeeze, got shape {arr.shape} from {path}")
    return arr

def text_flags(text: str) -> Tuple[int, int, str, str]:
    """
    Return:
      has_uncertainty (0/1),
      has_negation (0/1),
      laterality ('left'/'right'/'bilateral'/'none'),
      anatomy_group (coarse group)
    """
    t = f" {str(text).lower()} "
    has_unc = int(any(term in t for term in UNCERTAINTY_TERMS))
    has_neg = int(any(term in t for term in NEGATION_TERMS))

    lat = "none"
    for k, terms in LATERALITY_TERMS.items():
        if any(term in t for term in terms):
            lat = k
            break

    anatomy = "other"
    for group, kws in ANATOMY_GROUPS.items():
        if any(kw in t for kw in kws):
            anatomy = group
            break

    return has_unc, has_neg, lat, anatomy

def word_count(text: str) -> int:
    toks = re.findall(r"[A-Za-z0-9']+", str(text))
    return len(toks)


# ---------------------------
# ROI features from ct.npy/mask.npy
# ---------------------------

def compute_region_features(
    ct_vol: np.ndarray,
    mask_vol: np.ndarray,
    label_id: int,
    compute_intensity: bool = True,
    compute_components: bool = True,
) -> Dict[str, float]:
    """
    ct_vol, mask_vol: 3D arrays (D,H,W)
    mask_vol is expected to be integer-coded (0,1,2,...)
    """
    bin_mask = (mask_vol == label_id)
    vol = int(bin_mask.sum())
    D, H, W = mask_vol.shape

    feat: Dict[str, float] = {
        "label_id": int(label_id),
        "voxels": vol,
        "empty": 1 if vol == 0 else 0,
        "D": int(D),
        "H": int(H),
        "W": int(W),
    }

    def _fill_na(keys: Iterable[str]) -> None:
        for k in keys:
            feat[k] = float("nan")

    bbox_keys = [
        "zmin", "zmax", "ymin", "ymax", "xmin", "xmax",
        "bbox_d", "bbox_h", "bbox_w",
        "centroid_z", "centroid_y", "centroid_x",
        "centroid_z_norm", "centroid_y_norm", "centroid_x_norm",
        "slices_covered",
        "surface_voxels", "surface_to_volume",
    ]
    _fill_na(bbox_keys)

    if compute_intensity:
        _fill_na(["roi_mean", "roi_std", "roi_min", "roi_max", "roi_p05", "roi_p50", "roi_p95"])
    if compute_components:
        _fill_na(["components"])

    if vol == 0:
        return feat

    coords = np.argwhere(bin_mask)
    zmin, ymin, xmin = coords.min(axis=0)
    zmax, ymax, xmax = coords.max(axis=0)

    feat.update({
        "zmin": int(zmin), "zmax": int(zmax),
        "ymin": int(ymin), "ymax": int(ymax),
        "xmin": int(xmin), "xmax": int(xmax),
        "bbox_d": int(zmax - zmin + 1),
        "bbox_h": int(ymax - ymin + 1),
        "bbox_w": int(xmax - xmin + 1),
    })

    centroid = coords.mean(axis=0)
    feat.update({
        "centroid_z": float(centroid[0]),
        "centroid_y": float(centroid[1]),
        "centroid_x": float(centroid[2]),
        "centroid_z_norm": float(centroid[0] / (D - 1) if D > 1 else 0.0),
        "centroid_y_norm": float(centroid[1] / (H - 1) if H > 1 else 0.0),
        "centroid_x_norm": float(centroid[2] / (W - 1) if W > 1 else 0.0),
        "slices_covered": int(np.unique(coords[:, 0]).size),
    })

    # Surface voxels (approx) and surface/volume ratio
    try:
        from scipy.ndimage import binary_erosion
        eroded = binary_erosion(bin_mask, iterations=1)
        boundary = bin_mask & (~eroded)
        surface_vox = int(boundary.sum())
        feat["surface_voxels"] = surface_vox
        feat["surface_to_volume"] = float(surface_vox / vol) if vol > 0 else float("nan")
    except Exception:
        pass

    if compute_intensity:
        roi_vals = ct_vol[bin_mask]
        feat.update({
            "roi_mean": float(np.mean(roi_vals)),
            "roi_std": float(np.std(roi_vals)),
            "roi_min": float(np.min(roi_vals)),
            "roi_max": float(np.max(roi_vals)),
            "roi_p05": float(np.percentile(roi_vals, 5)),
            "roi_p50": float(np.percentile(roi_vals, 50)),
            "roi_p95": float(np.percentile(roi_vals, 95)),
        })

    if compute_components:
        try:
            from scipy.ndimage import label
            # 6-connectivity structure
            structure = np.zeros((3, 3, 3), dtype=np.uint8)
            structure[1, 1, :] = 1
            structure[1, :, 1] = 1
            structure[:, 1, 1] = 1
            _, ncomp = label(bin_mask.astype(np.uint8), structure=structure)
            feat["components"] = int(ncomp)
        except Exception:
            pass

    return feat


# ---------------------------
# Plot helpers
# ---------------------------

def plot_hist(values: np.ndarray, title: str, xlabel: str, out_path: Path, bins: int = 50, log1p: bool = False) -> None:
    import matplotlib.pyplot as plt

    v = values[~np.isnan(values)]
    if log1p:
        v = np.log1p(v)

    plt.figure(figsize=(7, 4.5))
    plt.hist(v, bins=bins)
    plt.title(title)
    plt.xlabel(xlabel + (" (log1p)" if log1p else ""))
    plt.ylabel("Count")
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()

def plot_bar(counter: Counter, title: str, out_path: Path, top_k: int = 20) -> None:
    import matplotlib.pyplot as plt

    items = counter.most_common(top_k)
    if not items:
        return
    labels, counts = zip(*items)

    plt.figure(figsize=(10, 4.5))
    plt.bar(range(len(labels)), counts)
    plt.xticks(range(len(labels)), labels, rotation=45, ha="right")
    plt.title(title)
    plt.ylabel("Count")
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()

def embed_text_tfidf(texts: List[str], max_features: int = 8000) -> np.ndarray:
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.decomposition import TruncatedSVD

    vectorizer = TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        max_features=max_features,
        ngram_range=(1, 2),
        min_df=2,
    )
    X = vectorizer.fit_transform(texts)

    # reduce sparse -> dense
    n_components = min(50, X.shape[1] - 1) if X.shape[1] > 1 else 1
    if n_components > 1:
        svd = TruncatedSVD(n_components=n_components, random_state=42)
        Xr = svd.fit_transform(X)
    else:
        Xr = X.toarray()
    return Xr.astype(np.float32)

def embed_text_sbert(texts: List[str], model_name: str) -> np.ndarray:
    from sentence_transformers import SentenceTransformer
    model = SentenceTransformer(model_name)
    emb = model.encode(texts, batch_size=32, show_progress_bar=True, normalize_embeddings=True)
    return np.asarray(emb, dtype=np.float32)

def run_tsne(
    X: np.ndarray,
    meta: pd.DataFrame,
    out_prefix: str,
    out_dir: Path,
    color_cols: List[str],
    perplexity: float = 30.0,
    random_state: int = 42,
) -> None:
    """
    Saves:
      - {out_prefix}_tsne_coords.csv
      - scatter plots colored by each column in color_cols
    """
    from sklearn.manifold import TSNE
    import matplotlib.pyplot as plt

    n = X.shape[0]
    if n < 5:
        print(f"[t-SNE] Too few samples ({n}), skip.")
        return

    perplexity = min(perplexity, max(2.0, (n - 1) / 3.0))
    tsne = TSNE(
        n_components=2,
        perplexity=perplexity,
        init="pca",
        learning_rate="auto",
        random_state=random_state,
    )
    Y = tsne.fit_transform(X)

    coords = meta.copy()
    coords["tsne_x"] = Y[:, 0]
    coords["tsne_y"] = Y[:, 1]
    coords.to_csv(out_dir / f"{out_prefix}_tsne_coords.csv", index=False)

    for col in color_cols:
        if col not in coords.columns:
            continue

        plt.figure(figsize=(7, 6))
        c = coords[col]

        if pd.api.types.is_numeric_dtype(c):
            # If numeric but only a few unique values, treat it as categorical (better legend)
            uniq_vals = sorted(pd.Series(c).dropna().unique().tolist())
            if len(uniq_vals) <= 12:
                for v in uniq_vals:
                    idx = (coords[col] == v).values
                    plt.scatter(coords.loc[idx, "tsne_x"], coords.loc[idx, "tsne_y"], s=10, label=str(v))
                plt.legend(title=col, bbox_to_anchor=(1.04, 1), loc="upper left")
            else:
                sc = plt.scatter(coords["tsne_x"], coords["tsne_y"], c=c, s=10)
                plt.colorbar(sc, label=col)
        else:
                # categorical -> plot per category (uses default matplotlib color cycle)
            cats = c.astype(str).fillna("NA")
            uniq = sorted(cats.unique())

            for u in uniq:
                idx = (cats == u).values
                plt.scatter(coords.loc[idx, "tsne_x"], coords.loc[idx, "tsne_y"], s=10, label=u)

            plt.legend(title=col, bbox_to_anchor=(1.04, 1), loc="upper left")

        plt.title(f"t-SNE colored by {col}")
        plt.tight_layout()
        plt.savefig(out_dir / f"{out_prefix}_tsne_{col}.png", dpi=220)
        plt.close()

def make_overlay_png(ct: np.ndarray, bin_mask: np.ndarray, out_path: Path, title: str = "") -> None:
    import matplotlib.pyplot as plt
    if bin_mask.sum() == 0:
        return

    areas = bin_mask.sum(axis=(1, 2))
    z = int(np.argmax(areas))
    img = ct[z]
    m = bin_mask[z].astype(np.uint8)

    plt.figure(figsize=(6, 6))
    plt.imshow(img, cmap="gray")
    try:
        plt.contour(m, levels=[0.5], linewidths=1)
    except Exception:
        pass
    plt.title(title + f" (z={z}, area={int(areas[z])})")
    plt.axis("off")
    plt.tight_layout()
    plt.savefig(out_path, dpi=220)
    plt.close()


# ---------------------------
# Main
# ---------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description="M3D-RefSeg (npy) EDA + t-SNE + QC")
    ap.add_argument("--csv", required=True, help="Path to M3D_RefSeg.csv")
    ap.add_argument("--npy_root", required=True, help="Path to M3D_RefSeg_npy/")
    ap.add_argument("--out_dir", default="./eda_out", help="Output directory")
    ap.add_argument("--max_rows", type=int, default=0, help="Limit CSV rows for quick debug (0=all)")
    ap.add_argument("--max_cases", type=int, default=0, help="Limit cases for image features (0=all)")

    ap.add_argument("--text_eda", action="store_true")
    ap.add_argument("--alignment_check", action="store_true")
    ap.add_argument("--compute_image_features", action="store_true")
    ap.add_argument("--compute_intensity", action="store_true")
    ap.add_argument("--compute_components", action="store_true")
    ap.add_argument("--n_overlay", type=int, default=0)

    ap.add_argument("--tsne_text", action="store_true")
    ap.add_argument("--tsne_text_mode", choices=["question", "label_desc", "question+label_desc"], default="label_desc")
    ap.add_argument("--tsne_unit", choices=["row", "region"], default="region")
    ap.add_argument("--embed_method", choices=["tfidf", "sbert"], default="tfidf")
    ap.add_argument("--sbert_model", default="all-MiniLM-L6-v2")
    ap.add_argument("--tsne_image", action="store_true")
    ap.add_argument("--tsne_perplexity", type=float, default=30.0)
    ap.add_argument("--seed", type=int, default=42)

    args = ap.parse_args()
    np.random.seed(args.seed)

    csv_path = Path(args.csv)
    npy_root = Path(args.npy_root)
    out_dir = Path(args.out_dir)

    tables_dir = out_dir / "tables"
    figs_dir = out_dir / "figs"
    overlay_dir = out_dir / "overlays"
    ensure_dir(tables_dir)
    ensure_dir(figs_dir)
    ensure_dir(overlay_dir)

    # Load CSV
    df = pd.read_csv(csv_path)
    if args.max_rows and args.max_rows > 0:
        df = df.iloc[: args.max_rows].copy()

    df["case_id"] = df["Image"].map(parse_case_id)
    df["region_id"] = df["case_id"].astype(str) + "__" + df["Mask_ID"].astype(str)

    # Text EDA (row-level)
    if args.text_eda:
        print("[EDA] Running text EDA...")
        df["q_words"] = df["Question"].map(word_count)
        df["a_words"] = df["Answer"].map(word_count)
        df["has_seg_token"] = df["Answer"].astype(str).str.contains(r"\[SEG\]", regex=True).astype(int)

        flags = df["Question"].map(text_flags)
        df["q_has_unc"] = flags.map(lambda x: x[0])
        df["q_has_neg"] = flags.map(lambda x: x[1])
        df["q_laterality"] = flags.map(lambda x: x[2])
        df["q_anatomy_group"] = flags.map(lambda x: x[3])

        row_cols = [
            "case_id", "Mask_ID", "region_id",
            "Question_Type", "q_words", "a_words", "has_seg_token",
            "q_has_unc", "q_has_neg", "q_laterality", "q_anatomy_group",
            "Question", "Answer",
        ]
        df[row_cols].to_csv(tables_dir / "rows_text_features.csv", index=False)

        summary = {
            "n_rows": int(len(df)),
            "n_cases": int(df["case_id"].nunique()),
            "n_regions": int(df["region_id"].nunique()),
            "question_type_counts": df["Question_Type"].value_counts(dropna=False).to_dict(),
            "has_seg_token_rate": float(df["has_seg_token"].mean()),
            "q_has_unc_rate": float(df["q_has_unc"].mean()),
            "q_has_neg_rate": float(df["q_has_neg"].mean()),
        }
        (tables_dir / "dataset_text_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

        plot_hist(df["q_words"].to_numpy(), "Question length (words)", "Words", figs_dir / "question_words_hist.png")
        plot_hist(df["a_words"].to_numpy(), "Answer length (words)", "Words", figs_dir / "answer_words_hist.png")
        plot_bar(Counter(df["Question_Type"].astype(str)), "Question_Type counts", figs_dir / "question_type_bar.png", top_k=10)
        plot_bar(Counter(df["q_anatomy_group"].astype(str)), "Question anatomy_group (heuristic)", figs_dir / "question_anatomy_group_bar.png", top_k=20)
        plot_bar(Counter(df["q_laterality"].astype(str)), "Question laterality (heuristic)", figs_dir / "question_laterality_bar.png", top_k=10)

        reg_counts = df.groupby("region_id").size().rename("qa_rows").reset_index()
        reg_counts.to_csv(tables_dir / "region_paraphrase_counts.csv", index=False)
        plot_hist(reg_counts["qa_rows"].to_numpy(), "QA rows per region (paraphrases)", "Count", figs_dir / "qa_rows_per_region_hist.png", bins=30)

    # Load label descriptions from text.json
    print("[INFO] Loading label descriptions from text.json (if available)...")
    case_to_text: Dict[str, Dict[str, str]] = {}
    unique_cases = sorted(df["case_id"].unique())
    if args.max_cases and args.max_cases > 0:
        unique_cases = unique_cases[: args.max_cases]

    for case_id in unique_cases:
        tj = npy_root / case_id / "text.json"
        m = safe_read_json(tj)
        if isinstance(m, dict):
            case_to_text[case_id] = {str(k): str(v) for k, v in m.items()}

    def lookup_label_desc(row) -> str:
        cid = row["case_id"]
        mid = str(int(row["Mask_ID"]))
        if cid in case_to_text and mid in case_to_text[cid]:
            return case_to_text[cid][mid]
        return ""

    df["label_desc"] = df.apply(lookup_label_desc, axis=1)

    # Region-level aggregation
    region_df = (
        df.groupby(["region_id", "case_id", "Mask_ID"], as_index=False)
          .agg(
              qa_rows=("Question", "size"),
              question_type_mode=("Question_Type", lambda x: int(pd.Series(x).mode().iloc[0]) if len(pd.Series(x).mode()) else int(x.iloc[0])),
              label_desc=("label_desc", lambda x: x.dropna().astype(str).iloc[0] if len(x.dropna()) else ""),
              questions_joined=("Question", lambda x: " || ".join(x.astype(str).tolist())),
              q_words_mean=("Question", lambda x: float(np.mean([word_count(t) for t in x]))),
              q_has_unc_rate=("Question", lambda x: float(np.mean([text_flags(t)[0] for t in x]))),
              q_has_neg_rate=("Question", lambda x: float(np.mean([text_flags(t)[1] for t in x]))),
          )
    )

    def region_anatomy(row) -> str:
        text = row["label_desc"] if row["label_desc"] else row["questions_joined"]
        return text_flags(text)[3]

    def region_laterality(row) -> str:
        text = row["label_desc"] if row["label_desc"] else row["questions_joined"]
        return text_flags(text)[2]

    region_df["anatomy_group"] = region_df.apply(region_anatomy, axis=1)
    region_df["laterality"] = region_df.apply(region_laterality, axis=1)
    region_df.to_csv(tables_dir / "regions_text_summary.csv", index=False)

    # Alignment check + image features
    image_feat_df = None
    if args.alignment_check or args.compute_image_features or args.n_overlay > 0:
        print("[EDA] Reading npy volumes for alignment/image features...")

        case_to_mask_ids: Dict[str, List[int]] = defaultdict(list)
        for cid, mid in df[["case_id", "Mask_ID"]].drop_duplicates().itertuples(index=False):
            case_to_mask_ids[str(cid)].append(int(mid))

        align_rows = []
        feat_rows = []
        overlay_candidates = []

        for cid in tqdm(unique_cases, desc="Cases"):
            case_dir = npy_root / cid
            ct_path = case_dir / "ct.npy"
            mask_path = case_dir / "mask.npy"
            tj_path = case_dir / "text.json"

            if not mask_path.exists():
                align_rows.append({"case_id": cid, "status": "missing_mask_npy"})
                continue

            try:
                mask_vol = load_npy_3d(mask_path)
            except Exception as e:
                align_rows.append({"case_id": cid, "status": f"mask_load_error:{e}"})
                continue

            mask_int = np.rint(mask_vol).astype(np.int32)
            ids_in_mask = sorted([int(x) for x in np.unique(mask_int).tolist() if int(x) != 0])
            ids_in_csv = sorted(set(case_to_mask_ids.get(cid, [])))

            text_map = safe_read_json(tj_path) if tj_path.exists() else None
            ids_in_text = sorted([int(k) for k in text_map.keys()]) if isinstance(text_map, dict) else []

            if args.alignment_check:
                align_rows.append({
                    "case_id": cid,
                    "ids_in_mask": ids_in_mask,
                    "ids_in_text": ids_in_text,
                    "ids_in_csv": ids_in_csv,
                    "missing_in_mask": sorted(list(set(ids_in_csv) - set(ids_in_mask))),
                    "missing_in_text": sorted(list(set(ids_in_csv) - set(ids_in_text))),
                    "extra_in_text_not_in_mask": sorted(list(set(ids_in_text) - set(ids_in_mask))),
                    "status": "ok",
                })

            ct_vol = None
            if args.compute_image_features or args.n_overlay > 0 or args.compute_intensity:
                if ct_path.exists():
                    try:
                        ct_vol = load_npy_3d(ct_path).astype(np.float32)
                    except Exception:
                        ct_vol = None

            if args.compute_image_features:
                if ct_vol is None and args.compute_intensity:
                    print(f"[WARN] {cid}: ct.npy missing/unreadable, intensity stats will be NaN.")

                for mid in ids_in_csv:
                    feat = {"case_id": cid, "Mask_ID": int(mid), "region_id": f"{cid}__{mid}"}
                    if ct_vol is None:
                        fake_ct = np.zeros_like(mask_int, dtype=np.float32)
                        feat.update(compute_region_features(fake_ct, mask_int, int(mid),
                                                           compute_intensity=False,
                                                           compute_components=args.compute_components))
                    else:
                        feat.update(compute_region_features(ct_vol, mask_int, int(mid),
                                                           compute_intensity=args.compute_intensity,
                                                           compute_components=args.compute_components))
                    feat_rows.append(feat)

                    if args.n_overlay > 0 and ct_vol is not None:
                        overlay_candidates.append((feat["voxels"], cid, mid))

        if args.alignment_check and align_rows:
            pd.DataFrame(align_rows).to_csv(tables_dir / "mask_text_alignment_report.csv", index=False)

        if args.compute_image_features and feat_rows:
            image_feat_df = pd.DataFrame(feat_rows)
            image_feat_df.to_csv(tables_dir / "regions_image_features.csv", index=False)

            plot_hist(image_feat_df["voxels"].to_numpy(), "ROI voxels per region", "Voxels", figs_dir / "roi_voxels_hist.png", bins=60)
            plot_hist(image_feat_df["voxels"].to_numpy(), "ROI voxels per region", "Voxels", figs_dir / "roi_voxels_hist_log1p.png", bins=60, log1p=True)
            plot_hist(image_feat_df["bbox_d"].to_numpy(), "ROI bbox depth (D)", "Depth", figs_dir / "roi_bbox_d_hist.png", bins=40)
            plot_hist(image_feat_df["bbox_h"].to_numpy(), "ROI bbox height (H)", "Height", figs_dir / "roi_bbox_h_hist.png", bins=40)
            plot_hist(image_feat_df["bbox_w"].to_numpy(), "ROI bbox width (W)", "Width", figs_dir / "roi_bbox_w_hist.png", bins=40)

            empty_df = image_feat_df[image_feat_df["empty"] == 1].copy()
            empty_df.to_csv(tables_dir / "empty_regions_after_prepare.csv", index=False)

        # overlays (pick top-N by ROI voxels)
        if args.n_overlay > 0 and overlay_candidates:
            overlay_candidates.sort(key=lambda x: x[0], reverse=True)
            chosen = overlay_candidates[: args.n_overlay]
            print(f"[QC] Saving {len(chosen)} overlay PNGs ...")

            for vox, cid, mid in tqdm(chosen, desc="Overlays"):
                case_dir = npy_root / cid
                ct_path = case_dir / "ct.npy"
                mask_path = case_dir / "mask.npy"
                if not ct_path.exists() or not mask_path.exists():
                    continue
                try:
                    ct_vol = load_npy_3d(ct_path).astype(np.float32)
                    mask_int = np.rint(load_npy_3d(mask_path)).astype(np.int32)
                except Exception:
                    continue

                bin_mask = (mask_int == int(mid))
                out_path = overlay_dir / f"{cid}__{mid}_vox{int(vox)}.png"
                make_overlay_png(ct_vol, bin_mask, out_path, title=f"{cid} Mask_ID={mid}")

    # t-SNE: Text
    if args.tsne_text:
        print("[t-SNE] Text embedding + t-SNE...")

        if args.tsne_unit == "row":
            meta = df[["case_id", "Mask_ID", "region_id", "Question_Type"]].copy()
            if args.tsne_text_mode == "question":
                texts = df["Question"].astype(str).tolist()
            elif args.tsne_text_mode == "label_desc":
                texts = df["label_desc"].astype(str).tolist()
            else:
                texts = (df["Question"].astype(str) + " || " + df["label_desc"].astype(str)).tolist()
        else:
            meta = region_df[["case_id", "Mask_ID", "region_id", "qa_rows", "question_type_mode", "anatomy_group", "laterality"]].copy()
            if args.tsne_text_mode == "question":
                texts = region_df["questions_joined"].astype(str).tolist()
            elif args.tsne_text_mode == "label_desc":
                texts = region_df["label_desc"].astype(str).tolist()
            else:
                texts = (region_df["label_desc"].astype(str) + " || " + region_df["questions_joined"].astype(str)).tolist()

        texts = [t if t.strip() else "EMPTY_TEXT" for t in texts]

        if args.embed_method == "tfidf":
            X = embed_text_tfidf(texts)
        else:
            try:
                X = embed_text_sbert(texts, args.sbert_model)
            except Exception as e:
                print(f"[WARN] SBERT failed ({e}), fallback to TF-IDF.")
                X = embed_text_tfidf(texts)

        out_prefix = f"text_{args.tsne_unit}_{args.tsne_text_mode}_{args.embed_method}"
        if args.tsne_unit == "row":
            color_cols = ["Question_Type"]
        else:
            color_cols = ["anatomy_group", "laterality", "qa_rows"]

        run_tsne(X, meta, out_prefix, figs_dir, color_cols, args.tsne_perplexity, args.seed)

    # t-SNE: Image numeric features
    if args.tsne_image:
        if image_feat_df is None:
            print("[t-SNE] --tsne_image requires --compute_image_features. Skipping.")
        else:
            print("[t-SNE] Image/ROI features + t-SNE...")

            meta = image_feat_df.merge(
                region_df[["region_id", "anatomy_group", "laterality", "qa_rows"]],
                on="region_id", how="left"
            )

            drop_cols = {"case_id", "region_id"}
            num_cols = [c for c in image_feat_df.columns if c not in drop_cols and pd.api.types.is_numeric_dtype(image_feat_df[c])]
            X = image_feat_df[num_cols].replace([np.inf, -np.inf], np.nan).fillna(0.0).values

            from sklearn.preprocessing import StandardScaler
            from sklearn.decomposition import PCA

            Xs = StandardScaler().fit_transform(X)
            pca_dim = min(20, Xs.shape[1])
            Xp = PCA(n_components=pca_dim, random_state=args.seed).fit_transform(Xs) if pca_dim >= 2 else Xs

            run_tsne(
                Xp.astype(np.float32),
                meta=meta[["case_id", "Mask_ID", "region_id", "anatomy_group", "laterality", "voxels", "empty"]],
                out_prefix="image_features",
                out_dir=figs_dir,
                color_cols=["anatomy_group", "laterality", "voxels", "empty"],
                perplexity=args.tsne_perplexity,
                random_state=args.seed,
            )

    print("\nDone. Outputs saved to:", out_dir.resolve())


if __name__ == "__main__":
    main()
